using Unity.AI.Navigation;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.AI;
using UnityEngine.SceneManagement;

/// <summary>Paint existing ground for navigation; never adds walkable geometry.</summary>
public static class DirtPathNavigationBake
{
    [MenuItem("Tools/Civil Craft/Update Dirt Path Navigation Areas")]
    private static void UpdateActiveScene()
    {
        if (EditorApplication.isPlayingOrWillChangePlaymode) return;
        Generate(SceneManager.GetActiveScene());
    }

    public static bool Generate(Scene scene)
    {
        if (!scene.IsValid() || !scene.isLoaded || Application.isPlaying) return false;
        int area = NavMesh.GetAreaFromName("DirtPath");
        if (area < 0)
        {
            Debug.LogError("DirtPath navigation area is missing. Reload project settings before baking.");
            return false;
        }

        // Validate first so missing colliders do not discard the previous setup.
        var paths = new System.Collections.Generic.List<CanyonDirtPaths>();
        foreach (GameObject root in scene.GetRootGameObjects())
            foreach (CanyonDirtPaths path in root.GetComponentsInChildren<CanyonDirtPaths>(true))
                if (path.isActiveAndEnabled && path.canyon != null && path.streets != null)
                {
                    Collider ground = path.canyon.GetComponent<Collider>();
                    if (ground == null || !ground.enabled || ground.isTrigger)
                    {
                        Debug.LogError($"{path.name}: dirt navigation needs an enabled, non-trigger canyon collider. No navigation volumes changed.", path);
                        return false;
                    }
                    paths.Add(path);
                }

        Undo.IncrementCurrentGroup();
        int undoGroup = Undo.GetCurrentGroup();
        Undo.SetCurrentGroupName("Update dirt path navigation areas");
        // Only delete containers marked as generated by this tool in this scene.
        foreach (GameObject root in scene.GetRootGameObjects())
            if (root.GetComponent<DirtPathNavigationVolumes>() != null)
                Undo.DestroyObjectImmediate(root);

        Physics.SyncTransforms();
        int count = 0;
        foreach (CanyonDirtPaths path in paths)
        {
            var container = new GameObject($"Dirt Navigation - {path.name}");
            SceneManager.MoveGameObjectToScene(container, scene);
            Undo.RegisterCreatedObjectUndo(container, "Create dirt navigation areas");
            Undo.AddComponent<DirtPathNavigationVolumes>(container).owner = path;
            Collider ground = path.canyon.GetComponent<Collider>();
            Bounds bounds = path.SurfaceBounds;
            float roadWidth = Mathf.Clamp(path.width, .01f, .2f) * Mathf.Min(bounds.size.x, bounds.size.z);

            for (int streetIndex = 0; streetIndex < Mathf.Min(16, path.streets.Length); streetIndex++)
            {
                CanyonDirtPaths.Street street = path.streets[streetIndex];
                Vector3 from = World(street.from, bounds);
                Vector3 to = World(street.to, bounds);
                Vector3 direction = to - from;
                float length = direction.magnitude;
                if (length < .01f) continue;
                float width = roadWidth * (street.widthMultiplier > 0f
                    ? Mathf.Clamp(street.widthMultiplier, .1f, 2f) : 1f);
                // Short boxes follow each bank's height rather than painting a
                // tall volume through roofs and the canyon floor beneath it.
                int sections = Mathf.Clamp(Mathf.CeilToInt(length / 2f), 1, 256);
                for (int i = 0; i < sections; i++)
                {
                    Vector3 a = Vector3.Lerp(from, to, (float)i / sections);
                    Vector3 b = Vector3.Lerp(from, to, (float)(i + 1) / sections);
                    Vector3 midpoint = (a + b) * .5f;
                    if (!Sample(ground, a, bounds, out Vector3 ga) ||
                        !Sample(ground, b, bounds, out Vector3 gb) ||
                        !Sample(ground, midpoint, bounds, out Vector3 gm)) continue;
                    float low = Mathf.Min(ga.y, gb.y, gm.y);
                    float high = Mathf.Max(ga.y, gb.y, gm.y);
                    if (high - low > .75f) continue; // Never bridge a cliff step.

                    GameObject box = new GameObject($"Street {streetIndex + 1} - {i + 1}");
                    box.layer = path.canyon.gameObject.layer;
                    box.transform.SetParent(container.transform, false);
                    box.transform.SetPositionAndRotation(
                        new Vector3(midpoint.x, (low + high) * .5f, midpoint.z),
                        Quaternion.LookRotation(direction.normalized, Vector3.up));
                    Undo.RegisterCreatedObjectUndo(box, "Create dirt navigation section");
                    NavMeshModifierVolume volume = Undo.AddComponent<NavMeshModifierVolume>(box);
                    volume.area = area;
                    volume.center = Vector3.zero;
                    volume.size = new Vector3(width, high - low + .8f, length / sections + .05f);
                    count++;
                }
            }
        }
        Undo.CollapseUndoOperations(undoGroup);
        EditorSceneManager.MarkSceneDirty(scene);
        Debug.Log($"Generated {count} DirtPath navigation sections for {paths.Count} dirt layouts. Bake the world NavMesh Surface, then save. Existing obstacles and gaps remain in force.");
        return true;
    }

    private static Vector3 World(Vector2 p, Bounds bounds) => new Vector3(
        bounds.min.x + p.x * bounds.size.x, 0f, bounds.min.z + p.y * bounds.size.z);

    private static bool Sample(Collider ground, Vector3 p, Bounds bounds, out Vector3 position)
    {
        var ray = new Ray(new Vector3(p.x, bounds.max.y + 1f, p.z), Vector3.down);
        if (ground.Raycast(ray, out RaycastHit hit, bounds.size.y + 2f) && hit.normal.y >= .85f)
        {
            position = hit.point;
            return true;
        }
        position = default;
        return false;
    }
}
